=== cla-pro/scholagest/tester/src/main/resources/xsd/scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="scenario" type="t_scenario" />
  <xs:complexType name="t_scenario">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="description" type="xs:string" />
      <xs:element name="baseURL" type="xs:string" />
      <xs:element name="calls" minOccurs="0" type="t_calls" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="t_calls">
    <xs:sequence>
      <xs:element name="call" minOccurs="0" maxOccurs="unbounded"
        type="t_call" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="t_call">
    <xs:sequence>
      <xs:element name="id" type="xs:string" />
      <xs:element name="url" type="xs:string" />
      <xs:element name="parameters" type="xs:string" />
      <xs:element name="httpMethod">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="GET" />
            <xs:enumeration value="POST" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="expectedResult" type="t_expectedResults" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="t_expectedResults">
    <xs:sequence>
      <xs:element name="result" minOccurs="0" maxOccurs="unbounded"
        type="t_result" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="t_result">
    <xs:sequence>
      <xs:element name="path" type="xs:string" />
      <xs:element name="value" type="xs:string" minOccurs="0" />
      <xs:element name="storeIn" type="xs:string" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== cla-pro/scholagest/scholagest-tester/src/main/resources/scenario/003_authenticate_and_validate.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd/scenario.xsd">
    <name>User service authentication with a valid token</name>
    <description></description>
    <baseURL>http://localhost:8080/scholagest-app/services</baseURL>
    <initializationFolder>initializer/tester/</initializationFolder>
    <calls>
        <call>
            <id>1 - Authenticate the credentials (admin/admin)</id>
            <url>/user/authenticate</url>
            <parameters>username=admin&amp;password=admin</parameters>
            <httpMethod>GET</httpMethod>
            <expectedResult>
                <result>
                	<path>token</path>
                	<storeIn>token</storeIn>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>2 - Authenticate the token</id>
            <url>/user/validateToken</url>
            <httpMethod>POST</httpMethod>
            <parameters>{token:'$$token$$'}</parameters>
            <expectedResult>
                <result>
                    <path>errorCode</path>
                    <value>null</value>
                </result>
            </expectedResult>
        </call>
    </calls>
</scenario>

=== cla-pro/scholagest/tester/src/main/resources/scenario/031_authorization_teacher.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd/scenario.xsd">
    <name>Scenario 1</name>
    <description></description>
    <baseURL>http://localhost:8080/scholagest-app/services</baseURL>
    <calls>
        <call>
            <id>1.1 - Authenticate admin</id>
            <url>/user/authenticate</url>
            <httpMethod>GET</httpMethod>
            <parameters>username=admin&password=admin</parameters>
            <expectedResult>
                <result>
                    <path>token</path>
                    <storeIn>adminToken</storeIn>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>1.2 - Authenticate class teacher</id>
            <url>/user/authenticate</url>
            <httpMethod>GET</httpMethod>
            <parameters>username=clavanchy&password=</parameters>
            <expectedResult>
                <result>
                    <path>token</path>
                    <storeIn>classTeacherToken</storeIn>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>1.3 - Authenticate other teacher</id>
            <url>/user/authenticate</url>
            <httpMethod>GET</httpMethod>
            <parameters>username=vparvex&password=</parameters>
            <expectedResult>
                <result>
                    <path>token</path>
                    <storeIn>otherTeacherToken</storeIn>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>2.1 - Check the authorization (getTeachers) with the admin rights</id>
            <url>/teacher/getTeachers</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$adminToken$$&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>2.2 - Check the authorization (getTeachers) with the class teacher rights</id>
            <url>/teacher/getTeachers</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$classTeacherToken$$&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>2.3 - Check the authorization (getTeachers) with the other teacher rights</id>
            <url>/teacher/getTeachers</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$otherTeacherToken$$&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>3.1 - Check the authorization (getTeachersInfo) with the admin rights</id>
            <url>/teacher/getTeachersInfo</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$adminToken$$&teachers=&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>3.2 - Check the authorization (getTeachersInfo) with the class teacher rights</id>
            <url>/teacher/getTeachersInfo</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$classTeacherToken$$&teachers=&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>3.3 - Check the authorization (getTeachersInfo) with the other teacher rights</id>
            <url>/teacher/getTeachersInfo</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$otherTeacherToken$$&teachers=&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>4.1 - Check the authorization (getProperties) with the admin rights</id>
            <url>/teacher/getProperties</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$adminToken$$&teacherKey=&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>4.2 - Check the authorization (getProperties) with the class teacher rights</id>
            <url>/teacher/getProperties</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$classTeacherToken$$&teacherKey=&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/0roperties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>4.3 - Check the authorization (getProperties) with the other teacher rights</id>
            <url>/teacher/getProperties</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$otherTeacherToken$$&teacherKey=&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info/properties/pTeacherFirstName</path>
                    <value>Cédric</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>5.1 - Check the authorization (setProperties) with the admin rights</id>
            <url>/teacher/setProperties</url>
            <httpMethod>POST</httpMethod>
            <parameters>{token=$$adminToken$$&teacherKey=&properties=pTeacherFirstName&properties=pTeacherLastName}</parameters>
            <expectedResult>
                <result>
                    <path>info</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>5.2 - Check the authorization (setProperties) with the class teacher rights</id>
            <url>/teacher/setProperties</url>
            <httpMethod>POST</httpMethod>
            <parameters>{token=$$classTeacherToken$$&teacherKey=&properties=pTeacherFirstName&properties=pTeacherLastName}</parameters>
            <expectedResult>
                <result>
                    <path>info</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>5.3 - Check the authorization (setProperties) with the other teacher rights</id>
            <url>/teacher/setProperties</url>
            <httpMethod>POST</httpMethod>
            <parameters>{token=$$otherTeacherToken$$&teacherKey=&properties=pTeacherFirstName&properties=pTeacherLastName}</parameters>
            <expectedResult>
                <result>
                    <path>errorCode</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>11.1 - Check the authorization (create) with the admin rights</id>
            <url>/teacher/create</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$adminToken$$&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>info</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>11.2 - Check the authorization (create) with the class teacher rights</id>
            <url>/teacher/create</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$classTeacherToken$$&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>errorCode</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>11.3 - Check the authorization (create) with the other teacher rights</id>
            <url>/teacher/create</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=$$otherTeacherToken$$&properties=pTeacherFirstName&properties=pTeacherLastName</parameters>
            <expectedResult>
                <result>
                    <path>errorCode</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
    </calls>
</scenario>

=== cla-pro/scholagest/scholagest-tester/src/main/resources/xsd/scenario1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd/scenario.xsd">
    <name>Scenario 1</name>
    <description></description>
    <baseURL>http://localhost:8080/scholagest-app/services</baseURL>
    <calls>
        <call>
            <id>Call 1</id>
            <url>/student/create</url>
            <parameters>token=1234&amp;keys=pStudentLastName&amp;keys=pStudentFirstName&amp;values=Lavanchy&amp;values=CÃ©dric</parameters>
            <httpMethod>GET</httpMethod>
            <expectedResult>
                <result>
                    <path>info/type</path>
                    <value>http://scholagest.net#tStudent</value>
                </result>
            </expectedResult>
        </call>
<!--         <call> -->
<!--             <id>Call 2</id> -->
<!--             <url></url> -->
<!--             <httpMethod>GET</httpMethod> -->
<!--             <expectedResult>{}</expectedResult> -->
<!--         </call> -->
    </calls>
</scenario>

=== cla-pro/scholagest/tester/src/main/resources/scenario/scenario1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd/scenario.xsd">
    <name>Scenario 1</name>
    <description></description>
    <baseURL>http://localhost:8080/scholagest-app/services</baseURL>
    <calls>
        <call>
            <id>1 - Create student</id>
            <url>/student/create</url>
            <parameters>token=1234&amp;keys=pStudentLastName&amp;keys=pStudentFirstName&amp;values=Lavanchy&amp;values=CÃ©dric</parameters>
            <httpMethod>GET</httpMethod>
            <expectedResult>
                <result>
                    <path>info/type</path>
                    <value>http://scholagest.net#tStudent</value>
                </result>
                <result>
                	<path>info/key</path>
                	<storeIn>studentKey</storeIn>
                </result>
            </expectedResult>
        </call>
        <call>
            <id>2 - Read student properties</id>
            <url>/student/getPersonalProperties</url>
            <httpMethod>GET</httpMethod>
            <parameters>token=1234&amp;studentKey=$$studentKey$$</parameters>
            <expectedResult>
            	<result>
            		<path>info/properties/pStudentLastName/value</path>
            		<value>Lavanchy</value>
            	</result>
            </expectedResult>
        </call>
    </calls>
</scenario>

=== cla-pro/scholagest/tester/src/main/resources/scenario/002_authenticate_and_validate_false.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd/scenario.xsd">
    <name>User service authentication with invalid token</name>
    <description></description>
    <baseURL>http://localhost:8080/scholagest-app/services</baseURL>
    <initializationFolder>initializer/tester/</initializationFolder>
    <calls>
        <call>
            <id>1 - Authenticate the token</id>
            <url>/user/validateToken</url>
            <httpMethod>POST</httpMethod>
            <parameters>{token:'abcdefghijklm'}</parameters>
            <expectedResult>
                <result>
                    <path>errorCode</path>
                    <value>0.0</value>
                </result>
            </expectedResult>
        </call>
    </calls>
</scenario>
